"""V71: all-around Race5 improvement from the V65 high-command policy.

V70 proved that a speed-only residual task can improve neither the deployed
speed branch nor the complete scorecard.  V71 keeps the experiment in the
full Race5 command distribution: V65 supplies the strong high-command
initialization, the V11 control-aware checkpoint anchors turns and recovery,
and V47 supplies the official-friction speed specialist.  The objective is
weighted toward usable forward speed while retaining line, heading, contact,
and stability terms.
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass

from mjlab_microduck.tasks.microduck_velocity_race5_frontier_env_cfg import (
    CONTROL_TEACHER_CHECKPOINT,
    SPEED_TEACHER_ONNX,
    make_microduck_velocity_race5_frontier_env_cfg,
    Race5HybridTeacherPpoCfg,
)
from mjlab_microduck.tasks.microduck_velocity_race5_constrained_env_cfg import (
    MicroduckRace5ConstrainedRlCfg,
)


V65_HIGH_WARMSTART = (
    "/home/juice/projects/microduck-lab/upstream/microduck_rl/"
    "protected_checkpoints/duckwing_v24/v65-high-exact-import.pt"
)
V67_COMPOSITE = (
    "/home/juice/projects/microduck-lab/releases/v67/"
    "duckwing-v67-joint-specialist-fusion.onnx"
)
# Generated by scripts/train-race5-v71-all-around.sh from V67's embedded
# standard actor.  Keeping this as a file makes the teacher path inspectable
# and lets DuckLab's existing Torch teacher run entirely on the GPU.
V67_HIGH_TEACHER_ONNX = (
    "/home/juice/projects/microduck-lab/upstream/microduck_rl/logs/"
    "rsl_rl/velocity_race5_v71_all_around/v67-speed-high.onnx"
)
V67_CONTROL_TEACHER_CHECKPOINT = (
    "/home/juice/projects/microduck-lab/upstream/microduck_rl/logs/"
    "rsl_rl/velocity_race5_v71_all_around/v67-control-teacher.pt"
)


@dataclass
class Race5V71AllAroundPpoCfg(Race5HybridTeacherPpoCfg):
    """Tighter teacher trust region for a full-command, all-around search."""

    teacher_checkpoint: str = V67_CONTROL_TEACHER_CHECKPOINT
    speed_teacher_onnx: str = V67_HIGH_TEACHER_ONNX
    teacher_loss_coef: float = 0.60
    teacher_loss_decay: float = 0.9999
    teacher_loss_floor: float = 0.12
    probe_loss_share: float = 0.60
    speed_command_threshold: float = 0.55
    smooth_turn_start: float = 0.08
    smooth_turn_end: float = 0.25


def make_microduck_velocity_race5_v71_all_around_env_cfg(play: bool = False):
    cfg = make_microduck_velocity_race5_frontier_env_cfg(play=play)

    # This is the controller used by the V67 qualification route.  Keeping
    # it in the train-time environment makes the lane/heading terms agree
    # with deployment instead of rewarding an easier, different correction.
    command = cfg.commands["twist"]
    command.yaw_kp = 0.70
    command.lateral_kp = 0.22
    command.yaw_kd = 0.07
    command.max_correction = 0.15

    # Push the complete scorecard together.  These terms remain smooth and
    # coexist with the frontier task's contact, gait, upright, and finish
    # rewards; no observation or action interface changes are introduced.
    cfg.rewards["race_speed_squared"].weight = 3.5
    cfg.rewards["race_forward_progress"].weight = 12.0
    cfg.rewards["race_launch_speed"].weight = 8.0
    cfg.rewards["race_usable_speed"].weight = 22.0
    cfg.rewards["race_usable_launch"].weight = 16.0
    cfg.rewards["race_lane_error"].weight = -22.0
    cfg.rewards["race_world_lateral_speed"].weight = -14.0
    cfg.rewards["race_heading_error"].weight = -22.0
    cfg.rewards["heading_hold"].weight = 18.0
    cfg.rewards["race_finish"].weight = 800.0
    cfg.rewards["race_elapsed"].weight = -1.5
    return cfg


MicroduckRace5V71AllAroundRlCfg = dataclasses.replace(
    MicroduckRace5ConstrainedRlCfg,
    algorithm=Race5V71AllAroundPpoCfg(
        class_name="mjlab_microduck.teacher_guided_ppo.TeacherGuidedPPO",
        value_loss_coef=1.0,
        use_clipped_value_loss=True,
        entropy_coef=0.0002,
        learning_rate=5.0e-7,
        desired_kl=5.0e-5,
        clip_param=0.006,
        num_learning_epochs=1,
        num_mini_batches=4,
        schedule="adaptive",
        gamma=0.99,
        lam=0.95,
        max_grad_norm=0.75,
    ),
    experiment_name="velocity_race5_v71_all_around",
    run_name="velocity_race5_v71_all_around",
    save_interval=25,
)
